#!/usr/bin/perl

use Test::More;
use Test::Harness;

my @COMMON        = glob "t/*.t";
my @BASIC_TESTS   = glob "t/basic/*.t";
my @DB_TESTS      = glob "t/db/*.t";
my @CORE_TESTS    = glob "t/core/*.t";
my @CORE_REPLICASETS = glob "t/core/Replicasets/*.t";
my @CORE_REPLICASETS_MEMBER = glob "t/core/Replicasets/Member/*.t";

runtests ( 
	       @COMMON      ,
		   @BASIC_TESTS , 
           @DB_TESTS    ,
           @CORE_TESTS  ,
 		   @CORE_REPLICASETS ,           
 		   @CORE_REPLICASETS_MEMBER ,
         );
