#!/usr/bin/env perl


BEGIN {
   use File::Basename        qw { dirname          };
   use File::Spec::Functions qw { splitdir rel2abs };
   my  @_BASEDIR = (splitdir( dirname( rel2abs( __FILE__ ) ) ) );
   pop @_BASEDIR;
   push @INC , join '/' , @_BASEDIR , 'lib';

};

use Mojo::IOLoop;
use mongopile::StatsCollector;

my $MPLoop = new Mojo::IOLoop();
   $MPLoop->recurring ( 20 =>  sub {
            my $stats_collector = new mongopile::StatsCollector();
            $stats_collector->get_status_for_all_replicasets();
            });
            
   $MPLoop->start;
   
